version: '3.9'

services:
  server:
    build: .
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - redis
    links: 
      - redis
    networks:
      - net
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'docker'
      POSTGRES_DB: 'docker'
    volumes:
       - data:/var/lib/postgresql/data
    restart: always
    networks:
      - net
  redis:
    image: redis:6.2-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes: 
      - cache:/data
    networks:
      - net
volumes:
  data: 
  cache:
    driver: local
networks:
  net: