version: '3.9'

services:
  server:
    build: .
    ports:
      - '8080:8080'
    restart: always
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'docker'
      POSTGRES_DB: 'docker'
    volumes:
       - data:/var/lib/postgresql/data
    restart: always     
  cache:
    image: redis:6.2-alpine
    restart: always
    volumes: 
      - cache:/data
volumes:
  data: 
  cache:
    driver: local